# RStudioを用いたプロジェクトの運用

## RStduioのプロジェクト機能 {#rstudio-project}

- `.Rproj`ファイル（実態はテキストファイル）
    - プロジェクトに関する設定が記述
- `.Rproj`ファイルのあるディレクトリが作業ディレクトリになる

### プロジェクトの作成

- プロジェクトの新規作成... `RStudioのメニュー --> File --> New Project`
- `usethis::usethis::create_project()`
- プロジェクトの種類に応じたテンプレート
   - パッケージ
   - Shinyアプリケーション
   - bookdown
   
### プロジェクト設定

**General**... 起動・終了時のRオブジェクトの扱いを指定します。これらのオプションはRの立ち上げ時に以前の状態を復元するのに便利ですが、代償として起動・終了にかかる時間が長くなることがあります。また、意図しないオブジェクトが存在することで生じる問題もあるので `No` にすることを勧めます。

| 項目 | 解説 | 推奨の設定 | 
|:-----|:-----|------------|
| Restore `.RData` into workspce at startup | 起動時に`.RData`に保存されたRオブジェクトを復元するか | `No` |
| Save workspace to `.RData` on exit | Rのセッション終了時に、Environmentに保存されたオブジェクトを`.RData`に保存するようにするオプション | `No` |

**Code Editing**

- タブ幅... **2** [The tidyverse style guide](https://style.tidyverse.org/) に従います。
- Ensure that source files and newline... ファイル末尾に改行を含めるようにします。
- Text encoding... `UTF-8`

**Git/SVN**

### コード規約とファイル命名規則 {#coding-rule}

ファイルにコードを記述する際のガイドラインを設けておくことは、多くの利益があります。例えば、将来の自分や複数人でコードを眺めたとき、統一された書き方であると可読性が高まります（逆に統一されていないコードでは可読性が低くなり、内容を把握するのに苦労します）。個人が好むルールを設定するのではなく、多くの人が従うガイドラインに沿うことが望ましいです。

**構文**

1. 省略を避ける
    - Rでは論理値として使われる `TRUE`, `FALSE`の頭文字を使って、それぞれを`T`,`F`として表現できますが、大文字のアルファベット一文字では検索がしにくくなってしまいます。
    - 単語の略語を用いると、それを知らない人がコードを見た時に意味がわからなくなる恐れがあります。
    - RStudioでは、`<key>tab</key>`の入力でオブジェクト名の補完が効くので、意味を掴めないオブジェクト名や引数名を定義するよりも多少長い名前を与えるのが親切です。
2. オブジェクト名に `.` を使わず、単語の区切りには `_` を使う
    - tidyverseのパッケージのルール

```
# 良い例
my_data

# 悪い例
MyData
my.data
```

3. 適宜スペースを入れる
    - 適当なスペースは、コードの見た目をよくします。スペースのないコードはどこに区切りがあるかわかり難く、スペースの多いコードでは冗長になってしまいます。スペースは半角スペース一つ分としましょう。また、スペースを入れる・入れないの判断は次のルールに従います。
    - スペースを入れる... カンマの後、`if`や`for`、`while`の後の括弧、`+`, `-`, `*`, `<-`, `=`, `==` などの演算子の前後。
    - スペースを入れない... `::`, `:::`, `$`, `@`, `[`, `[[`演算子や乗数を示す`^`、配列を定義する`:`演算子の前後。
    
```r
# 良い例
x <- c(1, NA, 3, 5)
mean(x, na.rm = TRUE)

for (i in 1:10) {
  i + 1
}

# 悪い例
iris $ Species
```


- パッケージによる補助... **lintr**, **styler**


### データ管理 {#data-management}

### 参考資料・URL

- [The tidyverse style guide](https://style.tidyverse.org/)
